Further update models
jessica-mitchell/nest-simulator pull request #12
Opened 2020-01-31 15:49 UTC by sarakonradi

This PR is based on #1374 and further updates the model files.

It: 
- Ensures keywords are consistently written in singular form
- Writes out abbreviations (e.g. `AC` and `DC`)
- Updates the `Device name`
- Adds an empty line between `EndUserDocs` and the class definition
- Corrects model names, such as `iaf_psc_exp_htum`

2020-02-12 10:20 UTC, jougs requested changes
Many thanks! This looks mostly good to me :-)

For the future, could you please @mention me (by writing `@jougs` in the description of the PR or a comment somewhere) when you're doing these kinds of things? That way I'd be alerted by email when something is ready for me to look at without any need to communicate that via other means. Thanks!

2020-02-12 10:20 UTC, jougs commented on models/ac_generator.h
> +This device produces an AC current sent by a CurrentEvent. The
```suggestion
This device produces AC input sent by CurrentEvents. The
```

Reasoning: AC already has a 'current' in it, cf. [PIN number, LCD display, ...](https://en.wikipedia.org/wiki/RAS_syndrome)

2020-02-12 10:20 UTC, jougs commented on models/bernoulli_connection.h
> +Sends
This needs to stay `Transmits`. Also in other files ending in `_connection.h`.

The logic is that neurons have the (single) event type they will send during the simulation under `Sends` and all event types they are able to handle under `Receives`. As synapses/connections only relay the events from the sender to the receiver, the have everything they can relay under `Transmits`.

2020-02-12 10:20 UTC, jougs commented on models/dc_generator.h
> +The dc_generator provides a constant DC Input to the connected node. The unit of the current is pA.
```suggestion
The dc_generator provides a constant DC input to the connected node. The unit of the current is pA.
```

2020-02-12 14:28 UTC, sarakonradi commented
@jougs Thanks for your suggestions! 

I added the `AC input`, `DC input` and `Transmits` changes. 

RAS syndrome can be painful. Hence, I removed the repetitions.

2020-02-12 15:49 UTC, jougs commented
Great!

Can you please again pull `jessica-mitchell:update_models_rst_format` into your branch and fix the conflicts? From my side this would then be good to go.

2020-02-14 10:36 UTC, jougs commented
@jessica-mitchell: could you please merge this? I'm fine with the changes now.
@sarakonradi: Merging this one into the branch nest/nest-simulator#1374 is based off should make Travis happy.

2020-03-04 16:11 UTC, merged